#!/usr/bin/env bash
set -euo pipefail

cd "$(dirname "$0")/.."

if [[ ! -x ./dist-newstyle/build/x86_64-linux/ghc-9.10.3/kurt-0.0.4/x/kurt/build/kurt/kurt ]]; then
  cabal v2-build >/dev/null
fi

exec ./dist-newstyle/build/x86_64-linux/ghc-9.10.3/kurt-0.0.4/x/kurt/build/kurt/kurt +RTS -N1
